### PR TITLE
Add support for Symfony 4

### PR DESCRIPTION
**Pull request by jvandesande**
* Change symfony dependency to the symfony components that are actually used

### CODE REVIEW

**Comment by jvandesande** [comment]
@sandermarechal @alexvandun @rjbijl

**Comment by jeffreymoelands** [comment]
+1

**Comment by yamitenshi** [comment]
+1

**Comment by djbfmeel** [comment]
+1

**Comment by sandermarechal** [comment]
Thanks! Merged and tagged as 1.0.3

**Pull request merged**
